package io.kite.domain;

public enum ErrorCode {
    NONE,
    INVALID_INPUT,
    STUDENT_ALREADY_REGISTERED,
    STUDENT_NOT_REGISTERED,
    COURSE_FULL,
    COURSE_CLOSED,
    COURSE_ALREADY_OPEN,
    COURSE_ALREADY_CLOSED,
    STUDENT_INACTIVE,
    INVALID_CAPACITY,
    INVALID_EMAIL,
    DUPLICATE_EMAIL,
    SCHEDULE_CONFLICT,
    PREREQUISITE_NOT_MET,
    ENROLLMENT_ALREADY_CANCELLED
}
